### ISSUE TITLE
Typing mistake on login causes gui hang up

### ISSUE THREAD

**Issue by djohs** [dm-drogeriemarkt/selavi#26]
If you make a typing mistake or enter incorrect username/password into the login form the GUI hangs up. In this case the progress roller will run forever. The only workaround is to reload the complete site in the browser.

![_thumb_114655](https://user-images.githubusercontent.com/6181229/42085348-7625620c-7b90-11e8-8553-ff63adc34548.png)

**Comment by mirkomack** [comment]
This issue has been resolved and should now behave as expected.
