### ISSUE TITLE
Add sample screenshot to documentation

### ISSUE THREAD

**Issue by deki** [dm-drogeriemarkt/selavi#5]
Could you add a sample screenshot from a SeLaVi instance that is connected to a Eureka with a complex service landscape to README.md? You can anonymize the service names but it would be great to get an idea how it should look like. It's also good for marketing purposes ;-).

Just tried it with a hello world service which wasn't really helpful:
![selavi](https://user-images.githubusercontent.com/858827/34440595-60055d60-ecb6-11e7-9385-50c47a8853a2.PNG)

**Comment by indyarni** [comment]
We feel the same way. The documentation lacks some look-and-feel. We will add sample screenshots soon.

**Comment by wicked539** [comment]
Added a screenshot with 48ba16487107c57bd23d6dbb1b04bd9c1e7eeeab

I agree that this needs A LOT more documentation, including a test system so that anyone can check out the application. Hopefully, we will have more time to invest in this project in the next couple of weeks!
